# Generated by Django 5.2.7 on 2025-10-27 11:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Admin Settings',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='Distance in km', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_hours', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('base_fare_per_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Routes',
                'ordering': ['distance'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Station code (e.g., BZA)', max_length=5, unique=True)),
                ('name', models.CharField(help_text='Full station name', max_length=100, unique=True)),
                ('city', models.CharField(help_text='City name', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(help_text='Unique train number', max_length=10, unique=True)),
                ('train_name', models.CharField(help_text='Train name', max_length=100)),
                ('train_type', models.CharField(choices=[('EXPRESS', 'Express'), ('RAPID', 'Rapid'), ('PASSENGER', 'Passenger'), ('SHATABDI', 'Shatabdi'), ('RAJDHANI', 'Rajdhani')], default='EXPRESS', max_length=20)),
                ('operator', models.CharField(default='Indian Railways', max_length=50)),
                ('total_coaches', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('seats_per_coach', models.IntegerField(default=72, validators=[django.core.validators.MinValueValidator(1)])),
                ('ac_first_seats', models.IntegerField(default=0)),
                ('ac_two_tier_seats', models.IntegerField(default=0)),
                ('ac_three_tier_seats', models.IntegerField(default=0)),
                ('sleeper_seats', models.IntegerField(default=0)),
                ('general_seats', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Trains',
                'ordering': ['train_number'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('passenger_phone', models.CharField(max_length=15)),
                ('passenger_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('passenger_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('journey_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('seat_class', models.CharField(choices=[('AC_FIRST', 'AC First Class'), ('AC_2_TIER', 'AC 2-Tier'), ('AC_3_TIER', 'AC 3-Tier'), ('SLEEPER', 'Sleeper'), ('GENERAL', 'General')], max_length=20)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_refundable', models.BooleanField(default=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(help_text='Departure time (HH:MM)')),
                ('arrival_time', models.TimeField(help_text='Arrival time (HH:MM)')),
                ('runs_on', models.CharField(default='0123456', help_text='Days: 0=Mon,1=Tue,2=Wed,3=Thu,4=Fri,5=Sat,6=Sun', max_length=7)),
                ('ac_first_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ac_two_tier_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ac_three_tier_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sleeper_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('general_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='railway_app.route')),
            ],
            options={
                'verbose_name_plural': 'Schedules',
                'ordering': ['departure_time'],
                'unique_together': {('route', 'departure_time')},
            },
        ),
        migrations.CreateModel(
            name='BookingLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text='e.g., 1A, 32C', max_length=5)),
                ('leg_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leg_sequence', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='railway_app.booking')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway_app.route')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway_app.schedule')),
            ],
            options={
                'verbose_name_plural': 'Booking Legs',
                'ordering': ['leg_sequence'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_routes', to='railway_app.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_routes', to='railway_app.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='railway_app.train'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('train', 'source', 'destination')},
        ),
    ]
